wallet_secret = "your secret key" # Wallet secret
is_mainnet = true
coin = "HYPE/USDC"                     # @107(SPOT)
interval = 5                      # Loop interval in seconds
database_url = "postgres://username:password@localhost/db_name"        # (Optional)Database URL

[bot_specific] # (Optional)Bot specific settings
threshold = 0.01
